name: Build

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  INSTANCE: 'Writerside/1'
  DOCKER_VERSION: '243.22562'
  CF_ACC_ID: ${{ secrets.CF_ACC_ID }}
  CF_API_TOK: ${{ secrets.CF_API_TOK }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_dir: ${{ steps.set-artifact.outputs.build_dir }}

    steps:
      - uses: actions/checkout@v4

      - name: Writerside Build
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Set Build Dir
        id: set-artifact
        run: |
          INSTANCE_ID=${{ env.INSTANCE#*/ }}
          INSTANCE_ID_UPPER=$(echo "$INSTANCE_ID" | tr '[:lower:]' '[:upper:]')
          echo "build_dir=artifacts/webHelp${INSTANCE_ID_UPPER}2-all" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to CF
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOK }}
          accountId: ${{ env.CF_ACC_ID }}
          command: pages deploy ${{ needs.build.outputs.build_dir }} --project-name=mmkb
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}