name: Build

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  INSTANCE: 'Writerside/1'
  DOCKER_VERSION: '243.22562'
  CF_ACC_ID: ${{ secrets.CF_ACC_ID }}
  CF_API_TOK: ${{ secrets.CF_API_TOK }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_dir: ${{ steps.extract.outputs.build_dir }}

    steps:
      - uses: actions/checkout@v4

      - name: Writerside Build
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.INSTANCE }}
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Extract Build Dir
        id: extract
        run: |
          INSTANCE_ID="${INSTANCE#*/}"
          BUILD_DIR="artifacts/webHelp${INSTANCE_ID^^}2-all"
          echo "build_dir=$BUILD_DIR" >> "$GITHUB_OUTPUT"

      - name: Check Build
        run: |
          echo "Checking build dir: ${BUILD_DIR}"
          ls -R "${BUILD_DIR}"

      - name: Upload Built
        uses: actions/upload-artifact@v4
        with:
          name: zip
          path: ${{ steps.extract.outputs.build_dir }}.zip
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: zip
          path: .

      - name: Unzip Writerside output
        run: |
          ZIP="${{ needs.build.outputs.build_dir }}.zip"
          mkdir -p "${{ needs.build.outputs.build_dir }}"
          unzip "$ZIP" -d "${{ needs.build.outputs.build_dir }}"

      - name: Deploy to CF
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CF_API_TOK }}
          accountId: ${{ env.CF_ACC_ID }}
          command: pages deploy --project-name=mmkb
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}